# Use an official Python runtime as a parent image
FROM python:3.9

# Set the working directory
WORKDIR /api

# Copy the current directory contents into the container at /api
COPY ./api /api

# Install the necessary packages
RUN pip install fastapi uvicorn scikit-learn

# Expose port 8000 to the outside world
EXPOSE 8000

# Run the FastAPI server
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
