services:
  fastapi:
    build:
      context: .
      dockerfile: ./api/Dockerfile.fastapi
    container_name: fastapi
    ports:
      - "8000:8000"
    volumes:
      - ../../models:/api/models 
  
  streamlit:
    build:
      context: .
      dockerfile: ./app/Dockerfile.streamlit
    container_name: streamlit
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
